apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jNW95MjB1Z2c4dWsuYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQo=
  db_username: YWRtaW4=
  db_password: RGV2b3BzMTIz
